#pragma once

#define SWITCH_A       (1 << 0)
#define SWITCH_B       (1 << 1)
#define SWITCH_X       (1 << 2)
#define SWITCH_Y       (1 << 3)
#define SWITCH_L       (1 << 4)
#define SWITCH_R       (1 << 5)
#define SWITCH_ZL      (1 << 6)
#define SWITCH_ZR      (1 << 7)
#define SWITCH_PLUS    (1 << 8)
#define SWITCH_MINUS   (1 << 9)
#define SWITCH_LSTICK  (1 << 10)
#define SWITCH_RSTICK  (1 << 11)
#define SWITCH_LPAD    (1 << 12)
#define SWITCH_RPAD    (1 << 13)
#define SWITCH_HOME    (1 << 14)
#define SWITCH_CAPTURE (1 << 15)
